server:
  port: "8080"
  readTimeout: 10s
  writeTimeout: 10s

db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "newfeed"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

jwt:
  secret: "your-secret-key"
  expirationHours: 24
  refreshSecret: "your-refresh-secret-key"
  refreshDuration: 168h

logLevel: "debug"
